#%RAML 1.0
version: v1
baseUri: https://anypoint.mulesoft.com/mocking/api/v1/links/b9712475-0a32-4e3d-a8a2-7d754f69ab1a/ # 
title: SDLC

/accounts:
 get:
   responses:
     200:
       body:
         application/json: 
           example: {"name":"mike"}
           
             